/**
 * Conversation and message-related TypeScript types
 * Handles both text and voice interactions with the AI
 */

/**
 * Message role in a conversation
 * - 'user': Message from the user
 * - 'assistant': Message from the AI
 * - 'system': System-generated message (e.g., conversation started)
 */
export type MessageRole = 'user' | 'assistant' | 'system';

/**
 * Message type/modality
 * - 'text': Text-based message
 * - 'voice': Voice message (with audio file)
 */
export type MessageType = 'text' | 'voice';

/**
 * Individual message within a conversation
 */
export interface Message {
  id: string;
  conversationId: string;
  role: MessageRole;
  type: MessageType;
  // Text content of the message
  content: string;
  // URL to audio file (for voice messages)
  audioUrl?: string | null;
  // Duration of audio in seconds (for voice messages)
  audioDuration?: number | null;
  createdAt: Date;
}

/**
 * Message response for API (with ISO date strings)
 */
export interface MessageResponse {
  id: string;
  conversationId: string;
  role: MessageRole;
  type: MessageType;
  content: string;
  audioUrl?: string | null;
  audioDuration?: number | null;
  createdAt: string; // ISO date string
}

/**
 * Conversation entity
 * Represents a chat session between user and AI
 */
export interface Conversation {
  id: string;
  userId: string;
  // Optional title for the conversation (can be auto-generated from first message)
  title?: string | null;
  // Summary of the conversation (generated by AI)
  summary?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Conversation response with message count
 */
export interface ConversationResponse {
  id: string;
  userId: string;
  title?: string | null;
  summary?: string | null;
  messageCount: number;
  // Preview of the last message
  lastMessage?: MessageResponse | null;
  createdAt: string; // ISO date string
  updatedAt: string; // ISO date string
}

/**
 * Detailed conversation with all messages
 */
export interface ConversationWithMessages extends ConversationResponse {
  messages: MessageResponse[];
}

/**
 * Request to create a new conversation
 */
export interface CreateConversationRequest {
  title?: string;
}

/**
 * Request to send a text message
 */
export interface SendTextMessageRequest {
  conversationId: string;
  content: string;
}

/**
 * Request to send a voice message
 * The audio file is sent as multipart/form-data
 */
export interface SendVoiceMessageRequest {
  conversationId: string;
  // Audio file will be in the multipart form data
  // This interface is for documentation purposes
}

/**
 * Response after sending a message
 * Includes both the user's message and the AI's response
 */
export interface SendMessageResponse {
  userMessage: MessageResponse;
  assistantMessage: MessageResponse;
}

/**
 * Request to generate voice from text (text-to-speech)
 */
export interface TextToSpeechRequest {
  text: string;
  // Optional voice ID from ElevenLabs (defaults to a preset voice)
  voiceId?: string;
}

/**
 * Response with generated audio URL
 */
export interface TextToSpeechResponse {
  audioUrl: string;
  duration: number; // Duration in seconds
}
